<a href="https://colab.research.google.com/github/ELDIE25/ANALYSIS/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Assignment:
#create 3 different variables holding at least 5 strings, 5 integers, 5 floats

strings = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
integers = [15, 32, 83, 34, 95]
floats = [12.8, 2.75, 7.14, 8.2, 4.0]

print(strings)
print(integers)
print(floats)

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
[15, 32, 83, 34, 95]
[12.8, 2.75, 7.14, 8.2, 4.0]

In [ ]:
#Assume you are the admission officer to a school(University Of Lagos) and you are to write a program to accept values from the student
#on the JAMB score which is highest score is 400 create your own cut off mark ..
#and use that cut off mark as a #comparision to the one inputted by the student seeking admission and give a message when the student passes the cut off mark
#and also a message when they dont..

jambScore = eval(input ('What is your JAMB score?: '))
if (jambScore >= 300 and jambScore <= 400):
   print('Congratulations, your admission status is successful')
else:
  print('Sorry, you do not qualify for the admission')

What is your JAMB score?: 180
Sorry, you do not qualify for the admission

In [ ]:
#multiply number from 1 to 10

multiply=1
for x in range(1,11):
    multiply = multiply * x
    print(multiply)

1
2
6
24
120
720
5040
40320
362880
3628800

In [ ]:
#Assume you are the database administrator at shoprite and you are just starting today being your first day and the goods bought,
#were 70 in total also the total sales of the day came to about 17,986,584. now you are to get the average sales goods bought,
#and also the previous day shoprite sold a total of 278 goods for 30,240,865 ..
#Check the sales per goods for shoprite on your first day and on the day before you resumed.. get the difference on the average,
#sales between those two days.
#Return your result in a meaningful manner of in a sentence to the HR.

first_day_goods = 70
first_day_sales = 17986584

first_day_avg = first_day_sales / first_day_goods
print(first_day_avg) # Output: 256951.2

previous_day_goods = 278
previous_day_sales = 30240865

previous_day_avg = previous_day_sales / previous_day_goods
print(previous_day_avg) # Output: 108779.01

difference = first_day_avg - previous_day_avg
print(difference)

message = f"The average sales per good on my first day was {first_day_avg:.2f}, while the previous day's average was {previous_day_avg:.2f}. This represents a difference of {difference:.2f} in average sales per good."
print(message)

256951.2
108780.08992805755
148171.11007194244
The average sales per good on my first day was 256951.20, while the previous day's average was 108780.09. This represents a difference of 148171.11 in average sales per good.

In [ ]:
number = 120

# For loop to find factors of 120
print("Factors of 120 using a for loop are:")
for i in range(1, number + 1):
    if number % i == 0: #mod qui represent le remainder
        print(i)

# While loop to find factors of 120
print("Factors of 120 using a while loop are:")
i = 1
while i <= number:
    if number % i == 0:
        print(i)
    i= i + 1

Factors of 120 using a for loop are:
1
2
3
4
5
6
8
10
12
15
20
24
30
40
60
120
Factors of 120 using a while loop are:
1
2
3
4
5
6
8
10
12
15
20
24
30
40
60
120

In [ ]:
def average (n1, n2, n3):
 answer = (n1 + n2 + n3)/3
 return answer

In [ ]:
 average (3,5,2)

3.3333333333333335

In [ ]:
sam = [4,5,9]
type (sam)

In [ ]:
sam [1]

In [ ]:
fuo = ['Vivian','tayo']

Create a dictionary containing 5 keys with each of them having 5 values and then perform slicing, .append, .pop, .insert, .remove, .extend and del

In [ ]:
diction = ['name', 'age', 'country', 'profession', 'day_of_birth']
diction

['name', 'age', 'country', 'profession', 'day_of_birth']

In [ ]:
diction = {
    'name':['Frida', 'Lilian', 'Comforte', 'Jennifer','Mary'],
    'age': [25,27,32,29,34],
    'country':['Benin','Nigeria','Ghana','Japan','China'],
    'profession':['lawyer', 'sales','tailor','data_analyst','programmer'],
    'day_of_birth':['monday', 'tuesday','wednesday','thursday','friday']
}
diction

{'name': ['Frida', 'Lilian', 'Comforte', 'Jennifer', 'Mary'],
 'age': [25, 27, 32, 29, 34],
 'country': ['Benin', 'Nigeria', 'Ghana', 'Japan', 'China'],
 'profession': ['lawyer', 'sales', 'tailor', 'data_analyst', 'programmer'],
 'day_of_birth': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']}

In [ ]:
#append
diction['name'].insert(5,'Ade')
diction['name']

['Frida', 'Lilian', 'Comforte', 'Jennifer', 'Mary', 'Ade']

In [ ]:
#pop
diction['country'].pop(2)
diction['country']

['Benin', 'Nigeria', 'Japan', 'China', 'USA']

In [ ]:
#insert
diction['name'].insert(2, 'tony')
diction['name']

['Frida', 'Lilian', 'tony', 'Comforte', 'Jennifer', 'Mary', 'Ade']

In [ ]:
#remove
diction['day_of_birth'].remove('friday')
diction['day_of_birth']

['monday', 'tuesday', 'wednesday', 'thursday']

In [ ]:
#slicing
diction['profession'][1:3]

['sales', 'tailor']

In [ ]:
import numpy as np
debby = [2,4,6,8,10,12,14,16,18,20]
debby

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
debby[3:-2]

[8, 10, 12, 14, 16]

In [ ]:
debby[4:7]

[10, 12, 14]

In [ ]:
odd = [[1,3,5,7,9], [11,13,15,17,19], [21,23,25,27,29]]
ph = np.array(odd)
ph

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [ ]:
ph [1,1:3]

array([13, 15])

ASSIGNMENT
Create a 2 dimensional array with the shape(5, 6)

In [ ]:
import numpy as np

arr = [[101,103,105,107,109,1111],
       [111,113,115,117,119,2222],
       [121,123,125,127,129,3333],
       [131,133,135,137,139,4444],
       [141,143,145,147,149,5555]]
fr = np.array(arr)
fr

array([[ 101,  103,  105,  107,  109, 1111],
       [ 111,  113,  115,  117,  119, 2222],
       [ 121,  123,  125,  127,  129, 3333],
       [ 131,  133,  135,  137,  139, 4444],
       [ 141,  143,  145,  147,  149, 5555]])

In [ ]:
fr.shape

(5, 6)

In [ ]:
fr.ndim

2

In [ ]:
fr[0:,0:5]

array([[101, 103, 105, 107, 109],
       [111, 113, 115, 117, 119],
       [121, 123, 125, 127, 129],
       [131, 133, 135, 137, 139],
       [141, 143, 145, 147, 149]])

In [ ]:
fr[0:,5]

array([1111, 2222, 3333, 4444, 5555])

In [ ]:
fr[:5,2]

array([105, 115, 125, 135, 145])

In [ ]:
#Create a pandas series using a dictionary having keys and 1 value each, then perform loc and iloc

import pandas as pd

data = {
    'name':['Mary','Peter','Paul','Abigail'],
    'country':['Paris','usa','Ghana','Nigeria']}

series = pd.Series(data)
series

name       [Mary, Peter, Paul, Abigail]
country    [Paris, usa, Ghana, Nigeria]
dtype: object

In [ ]:
series.loc['country']

['Paris', 'usa', 'Ghana', 'Nigeria']

In [ ]:
series.iloc[0]

['Mary', 'Peter', 'Paul', 'Abigail']

In [ ]:
import pandas as pd
data = {
  'Country': ['Nigeria', 'Ghana', 'USA', 'Canada', 'UK'],
    'Capital': ['Abuja', 'Accra', 'Washington', 'Ottawa', 'London'],
    'Postal code': [132, 5723, 5723, 242, 8242]
}
df = pd.DataFrame(data) #converting a dictionary into a pandas dataframe
df

   Country     Capital  Postal code
0  Nigeria       Abuja          132
1    Ghana       Accra         5723
2      USA  Washington         5723
3   Canada      Ottawa          242
4       UK      London         8242

In [ ]:
#Classwork: Create a pandas dataframe using a dictionary, the dataframe should comprise of 4 colunms and 5 rows.
#Perform del and .drop for both rows and columns

import pandas as pd

food =  {
'meats':['chicken','turkey','beef','pork','duck'],
'fishAndSeafoods':['salmon','carp','crab','lobster','shrimp'],
'veggies':['cabbage','potato','eggplant','onion','carrot'],
'fruits':['banana','mango','orange','pawpaw','watermelon']
}
df = pd.DataFrame(food)
df

     meats fishAndSeafoods   veggies      fruits
0  chicken          salmon   cabbage      banana
1   turkey            carp    potato       mango
2     beef            crab  eggplant      orange
3     pork         lobster     onion      pawpaw
4     duck          shrimp    carrot  watermelon

In [ ]:
del df['fruits']
df

     meats fishAndSeafoods   veggies
0  chicken          salmon   cabbage
1   turkey            carp    potato
2     beef            crab  eggplant
3     pork         lobster     onion
4     duck          shrimp    carrot

In [ ]:
df.drop (1, axis=0)

     meats fishAndSeafoods   veggies
0  chicken          salmon   cabbage
2     beef            crab  eggplant
3     pork         lobster     onion
4     duck          shrimp    carrot

In [ ]:
df.drop('meats', axis =1)

  fishAndSeafoods   veggies
0          salmon   cabbage
1            carp    potato
2            crab  eggplant
3         lobster     onion
4          shrimp    carrot

create a dataframe that holds about minimum of 10 customers .. and the column names should go as follows
Name , Current Amount, Withdrawal Amount and Age Of Customer ..
Now Create a method,way,function to do a subtraction to get the balance of each user in the dataframe and create a column that
all the users balance after withdrawal can be found.also give the descriptive summary of the dataframe , give the total number of rows and columns in a printed manner,
return the new dataframe holding the new column which is the balance column and also perform descriptive summary on it

In [ ]:
import pandas as pd
import numpy as np

dataFrame = {
    'Name': ['Abigail', 'Peter', 'Paul', 'Mary', 'Frida','Leona','Ade','Adeline','John','Philip'],
    'Current Amount': [18470, 203980, 3034780, 4020, 2334, 872642,12323,1399843,343413,2948],
    'Withdrawal Amount':[5000, 20000, 1000000, 1000, 1500, 12000, 5000, 300000, 45000, 500],
    'Age of Customer':[23, 34, 20, 22, 36, 20, 33, 25, 31, 28]
}

df = pd.DataFrame(dataFrame)
df

      Name  Current Amount  Withdrawal Amount  Age of Customer
0  Abigail           18470               5000               23
1    Peter          203980              20000               34
2     Paul         3034780            1000000               20
3     Mary            4020               1000               22
4    Frida            2334               1500               36
5    Leona          872642              12000               20
6      Ade           12323               5000               33
7  Adeline         1399843             300000               25
8     John          343413              45000               31
9   Philip            2948                500               28

In [ ]:
def substract (df,column1,column2):
    df['balance'] = df[column1] - df[column2]
    return df

In [ ]:
substract(df, 'Current Amount' ,'Withdrawal Amount')

      Name  Current Amount  Withdrawal Amount  Age of Customer  balance
0  Abigail           18470               5000               23    13470
1    Peter          203980              20000               34   183980
2     Paul         3034780            1000000               20  2034780
3     Mary            4020               1000               22     3020
4    Frida            2334               1500               36      834
5    Leona          872642              12000               20   860642
6      Ade           12323               5000               33     7323
7  Adeline         1399843             300000               25  1099843
8     John          343413              45000               31   298413
9   Philip            2948                500               28     2448

In [ ]:
df.describe()

       Current Amount  Withdrawal Amount  Age of Customer       balance
count    1.000000e+01          10.000000        10.000000  1.000000e+01
mean     5.894753e+05      139000.000000        27.200000  4.504753e+05
std      9.784458e+05      316124.535938         6.014797  6.818731e+05
min      2.334000e+03         500.000000        20.000000  8.340000e+02
25%      6.095750e+03        2375.000000        22.250000  4.095750e+03
50%      1.112250e+05        8500.000000        26.500000  9.872500e+04
75%      7.403348e+05       38750.000000        32.500000  7.200848e+05
max      3.034780e+06     1000000.000000        36.000000  2.034780e+06

In [ ]:
df.shape

(10, 5)

In [ ]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/lorenzodenisi/Heart-Failure-Clinical-Records/master/heart_failure_clinical_records_dataset.csv')
data

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

In [ ]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
age,299.0,60.833893,11.894809,40.0,51.0,60.0,70.0,95.0
anaemia,299.0,0.431438,0.496107,0.0,0.0,0.0,1.0,1.0
creatinine_phosphokinase,299.0,581.839465,970.287881,23.0,116.5,250.0,582.0,7861.0
diabetes,299.0,0.418060,0.494067,0.0,0.0,0.0,1.0,1.0
ejection_fraction,299.0,38.083612,11.834841,14.0,30.0,38.0,45.0,80.0
high_blood_pressure,299.0,0.351171,0.478136,0.0,0.0,0.0,1.0,1.0
platelets,299.0,263358.029264,97804.236869,25100.0,212500.0,262000.0,303500.0,850000.0
serum_creatinine,299.0,1.393880,1.034510,0.5,0.9,1.1,1.4,9.4
serum_sodium,299.0,136.625418,4.412477,113.0,134.0,137.0,140.0,148.0
sex,299.0,0.648829,0.478136,0.0,0.0,1.0,1.0,1.0
smoking,299.0,0.321070,0.467670,0.0,0.0,0.0,1.0,1.0
time,299.0,130.260870,77.614208,4.0,73.0,115.0,203.0,285.0
DEATH_EVENT,299.0,0.321070,0.467670,0.0,0.0,0.0,1.0,1.0

In [ ]:
import pandas as pd
data = pd.read_csv('/content/supermarket_sales.csv')
data

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Month,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,May,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,Aug,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,Mar,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,Jan,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,Aug,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,Jan,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,Feb,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,Sep,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,Feb,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,Feb,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [ ]:
data.groupby('City')['Branch'].value_counts().sort_values(ascending=False)

City       Branch
Yangon     A         340
Mandalay   B         332
Naypyitaw  C         328
Name: count, dtype: int64

In [ ]:
data.groupby('Product line')['Rating'].mean().sort_values(ascending=False)

Product line
Food and beverages        7.113218
Fashion accessories       7.029213
Health and beauty         7.003289
Electronic accessories    6.924706
Sports and travel         6.916265
Home and lifestyle        6.837500
Name: Rating, dtype: float64

In [ ]:
data['Total'].mean()

np.float64(322.966749)

In [ ]:
data.groupby('Product line')['Unit price'].sum().sort_values(ascending=False)

Product line
Fashion accessories       10173.35
Food and beverages         9745.54
Sports and travel          9460.88
Electronic accessories     9103.77
Home and lifestyle         8850.71
Health and beauty          8337.88
Name: Unit price, dtype: float64

In [ ]:
import pandas as pd
data = pd.read_csv('/content/supermarket_sales.csv')
data

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Month,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,May,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,Aug,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,Mar,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,Jan,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,Aug,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,Jan,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,Feb,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,Sep,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,Feb,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,Feb,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [ ]:
Jan = data[data['Month'] == 'Jan']
Jan['Product line'].value_counts()

Product line
Sports and travel         49
Electronic accessories    45
Fashion accessories       44
Food and beverages        44
Home and lifestyle        41
Health and beauty         39
Name: count, dtype: int64

In [ ]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (4.13.2)